# Name of your site (displayed in the header)
name: Centro Médico Gramenet

# Short bio or description (displayed in the header)
description: Certificados médicos y psicotécnicos
alternativa: Permiso de conducción, armas y otros
obtenciones: 35

# Info
info1: Sin cita previa
info2: Revisión médica en 15 min
info3: No es necesaria foto, se hace en el centro
info4: Tu Carnet renovado al momento

# Permisos
p1: Coche
p2: Moto
p3: Camión
p4: Náutica
p5: Ciclismo
p6: Seguridad privada
p7: Perros peligrosos
p8: Permiso de armas
p9: Laborales y deportivos

# Horari
mananas: de 10h a 14h
tardes: De 16:30h a 19:30h

# Santa Coloma
city: Santa Coloma de Gramanet
location: c/ Llorenç Serra, 5, Entlo. 3ª, Santa Coloma de Gramanet
phone: +34 933 86 54 44
whatsapp: 652075255
email: centromedico.gramenet@gmail.com

# Badalona
city2: Badalona
location2: c/ Temple, 24, 08911, Badalona
phone2: +34 933 844 892
email2: correu@gmail.com

# URL of your avatar or profile pic (you could use your GitHub profile pic)
avatar: 
logo: 

# Sections
section1: Revisiones
section1d: Tipos de Certificados y Preguntas frecuentes
section2: Galeria
section2d: galeria de Fotos del Centro
section3:
section3d:
section4:
section4d:
section5:
section5d:
section6: Nosotros
section6d: Más Información

# Includes an icon in the footer for each username you enter
footer-links:
  dribbble:
  email:
  facebook:
  instagram:
  twitter:
  linkedin:
  pinterest:
  youtube:
  googleplus: 
  tripadvisor:
  flickr:
  github:
  behance:  
  stackoverflow: # your stackoverflow profile, e.g. "users/50476/bart-kiers"
  rss: true

# Enter your Disqus shortname (not your username) to enable commenting on posts
# You can find your shortname on the Settings page of your Disqus account
disqus:

# Enter your Google Analytics web tracking code (e.g. UA-2110908-2) to activate tracking
google_analytics: UA-139209303-1 

# Your website URL (e.g. http://barryclark.github.io or http://www.barryclark.co)
# Used for Sitemap.xml and your RSS feed
url: https://centromedicogramanet.com

# If you're hosting your site at a Project repository on GitHub pages
# (http://yourusername.github.io/repository-name)
# and NOT your User repository (http://yourusername.github.io)
# then add in the baseurl here, like this: "/repository-name"
baseurl: ""

#
# !! You don't need to change any of the configuration flags below !!
#

permalink: /:title/

# The release of Jekyll Now that you're using
version: v1.2.0

# Jekyll 3 now only supports Kramdown for Markdown
kramdown:
  # Use GitHub flavored markdown, including triple backtick fenced code blocks
  input: GFM
  # Jekyll 3 and GitHub Pages now only support rouge for syntax highlighting
  syntax_highlighter: rouge
  syntax_highlighter_opts:
    # Use existing pygments syntax highlighting css
    css_class: 'highlight'

# Set the Sass partials directory, as we're using @imports
sass:
  style: :expanded # You might prefer to minify using :compressed

# Use the following plug-ins
gems:
  - jekyll-sitemap # Create a sitemap using the official Jekyll sitemap gem
  - jekyll-feed # Create an Atom feed using the official Jekyll feed gem

# Exclude these files from your production _site
exclude:
  - Gemfile
  - Gemfile.lock
  - LICENSE
  - README.md
  - CNAME

# Defaults
defaults:
  -
    scope:
      path: "assets/bio"
    values:
      image: true
